{{ $componentFullName := printf "%s-%s-%s" .Values.app .Values.component .Values.type }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $componentFullName | printf "%s-secret" | quote }}
  labels:
{{ include "basicLabels" . | indent 4 }}
data:
{{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
